# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Define variables:
    env: 
      name: Ben

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, $name!
          echo Actor: ${{ github.actor }}
          echo Committed By: ${{ github.event.commits[0].author.name }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  weather:
    runs-on: ubuntu-latest
    env:
      cityname: Vancouver
      postalcode: V5Y1V4
      api_secret: ${{ secrets.WEATHERSTACK_SECRET }}
      full_url: ${{ secrets.WEATHERSTACK_URL }}
    steps:
      - name: Current Weather
        run: | 
          curl -s --url http://api.weatherstack.com/current?access_key=$api_secret&query=$postalcode
          echo $cityname
      - name: Test Weather
        run: | 
          curl -s --url http://api.weatherstack.com/current?access_key=$api_secret&query=$cityname
          echo $postalcode
      - name: Encode Weather
        run: | 
          curl -s --url http://api.weatherstack.com/current?access_key=$api_secret%26query=$cityname
          echo $postalcode
          echo $cityname
      - name: Full URL
        run: | 
          curl -s --url $full_url
          echo $postalcode
          echo $cityname
  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
